/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uygulama;

import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import sınıflar.KullaniciProperty;
import sınıflar.DB;
import java.sql.SQLException;
import java.util.Random;

import javax.swing.JOptionPane;

/**
 *
 * @author Morgoyun
 */
public class KullaniciGiris extends javax.swing.JFrame {

    /**
     * Creates new form KullaniciGiris
     */
    public KullaniciGiris() {
        initComponents();

//        lblDogrula.setText(String.valueOf(db.rndSayi));

        
       

    }




    DB db = new DB();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        kullaniciPanel = new javax.swing.JPanel();
        lblAd = new javax.swing.JLabel();
        lblSifre = new javax.swing.JLabel();
        txtKullaniciAd = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtKullaniciSifre = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        txtAdKayit = new javax.swing.JTextField();
        txtSifreKayit = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtAdKontrol = new javax.swing.JTextField();
        txtSifreKontrol = new javax.swing.JTextField();
        txtYeniSifre = new javax.swing.JTextField();
        txtYeniSifreTekrar = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        kullaniciPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Kullanıcı Giriş Paneli"));

        lblAd.setText("AD");

        lblSifre.setText("ŞİFRE");

        jButton1.setText("Giriş");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtKullaniciSifre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKullaniciSifreKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout kullaniciPanelLayout = new javax.swing.GroupLayout(kullaniciPanel);
        kullaniciPanel.setLayout(kullaniciPanelLayout);
        kullaniciPanelLayout.setHorizontalGroup(
            kullaniciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kullaniciPanelLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(kullaniciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSifre, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAd, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(33, 33, 33)
                .addGroup(kullaniciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtKullaniciAd)
                    .addComponent(txtKullaniciSifre)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        kullaniciPanelLayout.setVerticalGroup(
            kullaniciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kullaniciPanelLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(kullaniciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtKullaniciAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kullaniciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKullaniciSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSifre))
                .addGap(27, 27, 27)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("GİRİŞ", kullaniciPanel);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Kullanıcı Kayıt Paneli"));

        jButton2.setText("KAYIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("AD");

        jLabel2.setText("ŞİFRE");

        jButton5.setText("Şifre");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel3.setText("Random Şifre Al");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAdKayit, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSifreKayit, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAdKayit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtSifreKayit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("KAYIT", jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Şifre Değiştirme"));

        txtYeniSifre.setEnabled(false);

        txtYeniSifreTekrar.setEnabled(false);

        jButton3.setText("Şifre Değiştir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Kullanıcı Doğrula");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel4.setText("Ad");

        jLabel5.setText("Şifre");

        jLabel6.setText("Şifre");

        jLabel7.setText("Şifre Tekrar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtYeniSifreTekrar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtYeniSifre, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSifreKontrol, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtAdKontrol, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAdKontrol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSifreKontrol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtYeniSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtYeniSifreTekrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ŞİFRE DEĞİŞTİR", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
KullaniciProperty kp = new KullaniciProperty();
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
        String adi = txtKullaniciAd.getText().trim();
        String sifre = txtKullaniciSifre.getText().trim();
//        String dogrula = txtDogrula.getText().trim();
//        kp.setDogrula(dogrula);
//        boolean dogruMu=false;

        kp.setkAdi(adi);
        kp.setkSifre(sifre);

     MainForm main=new MainForm();
        db.baglan(kp.getkAdi(), kp.getkSifre());
        if (db.kontrol) {
            this.dispose();
            this.setVisible(false);
//form açılmadan ürün uyarısı ver!

             
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Bilgilerinizi Kontrol Ediniz!");
        txtKullaniciSifre.setText("");
        
        
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        //kayıt ad soy giriş adsoylar için validatorler metodlaştırılacak!!!!
        String adi = txtAdKayit.getText().trim();
        String sifre = txtSifreKayit.getText().trim();

        kp.setkAdi(adi);
        kp.setkSifre(sifre);

        try {
            String query = "insert into kullanicilar  values(null,'" + kp.getkAdi() + "','" + kp.getkSifre() + "')";
            int i = db.baglan().executeUpdate(query);
            JOptionPane.showMessageDialog(rootPane, "Kayıt işlemi gerçekleştirildi.Giriş yapınız.");
            jTabbedPane1.setSelectedIndex(0);
            txtKullaniciAd.setText("");
            txtKullaniciAd.requestFocus();
            txtKullaniciSifre.setText("");

        } catch (SQLException ex) {

            System.out.println("kayıt hatası: " + ex);
            if (ex.toString().contains("SQLITE_CONSTRAINT_UNIQUE")) {
                JOptionPane.showMessageDialog(rootPane, "aynı kullanıcı ismi zaten var!");
                txtAdKayit.setText("");
                txtAdKayit.requestFocus();
            }
        } finally {
            db.kapat();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    public String kullaniciNo = "";
    public String kullaniciAdi = "";
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        KullaniciProperty kp = new KullaniciProperty();
        kp.setkAdi(txtAdKontrol.getText());
        kp.setkSifre(txtSifreKontrol.getText());
        try {
            String query = "select * from kullanicilar ";
            ResultSet rs = db.baglan().executeQuery(query);
            while (rs.next()) {
                //şifre ve kadi eşleşmeleri ayrı ayrı kontrol edip daha efektif yapılabilir
                if ((kp.getkAdi().equals(rs.getString("kAd")) && kp.getkSifre().equals(rs.getString("kSifre")))) {
                    kullaniciNo = rs.getString("kNo");
                    kullaniciAdi = rs.getString("kAd");
                    txtYeniSifre.setEnabled(true);
                    txtYeniSifreTekrar.setEnabled(true);

                }
            }
        } catch (SQLException e) {
            System.err.println("kullanici kontrol ederken hata! " + e);
        } finally {
            db.kapat();
        }


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        KullaniciProperty kp = new KullaniciProperty();
        if (txtYeniSifre.getText().equals(txtYeniSifreTekrar.getText())) {
            try {
                String query = "update kullanicilar set kSifre='" + txtYeniSifreTekrar.getText() + "' where kNo='" + kullaniciNo + "'";
                int degistirmeSonuc = db.baglan().executeUpdate(query);
                if (degistirmeSonuc > 0) {
                    JOptionPane.showMessageDialog(rootPane, "şifreniz değiştirildi sn:  " + kullaniciAdi);
                    txtAdKontrol.setText("");
                    txtSifreKontrol.setText("");
                    txtYeniSifre.setText("");
                    txtYeniSifreTekrar.setText("");
                }
            } catch (HeadlessException | SQLException e) {
                System.err.println("Şifre Değiştirirken Hata! " + e);
            } finally {
                db.kapat();
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "şifreler uyuşmuyor!");
            txtYeniSifreTekrar.requestFocus();
        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtKullaniciSifreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKullaniciSifreKeyReleased
 if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
        String adi = txtKullaniciAd.getText().trim();
        String sifre = txtKullaniciSifre.getText().trim();
//        String dogrula = txtDogrula.getText().trim();
//        kp.setDogrula(dogrula);
//        boolean dogruMu=false;

        kp.setkAdi(adi);
        kp.setkSifre(sifre);

     MainForm main=new MainForm();
        db.baglan(kp.getkAdi(), kp.getkSifre());
        if (db.kontrol) {
            this.dispose();
            this.setVisible(false);
//form açılmadan ürün uyarısı ver!

             
        }
        }
    }//GEN-LAST:event_txtKullaniciSifreKeyReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

txtSifreKayit.setText(""+new Random().nextInt(99999));
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KullaniciGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KullaniciGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KullaniciGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KullaniciGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KullaniciGiris().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel kullaniciPanel;
    private javax.swing.JLabel lblAd;
    private javax.swing.JLabel lblSifre;
    private javax.swing.JTextField txtAdKayit;
    private javax.swing.JTextField txtAdKontrol;
    private javax.swing.JTextField txtKullaniciAd;
    private javax.swing.JPasswordField txtKullaniciSifre;
    private javax.swing.JTextField txtSifreKayit;
    private javax.swing.JTextField txtSifreKontrol;
    private javax.swing.JTextField txtYeniSifre;
    private javax.swing.JTextField txtYeniSifreTekrar;
    // End of variables declaration//GEN-END:variables
}
